# Generated by Django 5.2 on 2025-05-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Arbeit', 'Arbeit'), ('Haushalt', 'Haushalt'), ('Gesundheit', 'Gesundheit'), ('Sonstiges', 'Sonstiges')], default='Sonstiges', max_length=20, verbose_name='Kategorie'),
        ),
    ]
