# Generated by Django 5.2 on 2025-05-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_reminder_sent_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
