# Generated by Django 5.2 on 2025-05-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_created_at_alter_task_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('subject', models.CharField(max_length=200, verbose_name='Betreff')),
                ('message', models.TextField(verbose_name='Nachricht')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gesendet am')),
            ],
            options={
                'verbose_name': 'Kontaktnachricht',
                'verbose_name_plural': 'Kontaktnachrichten',
            },
        ),
    ]
