# Generated by Django 5.2.1 on 2025-05-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Arbeit', 'Arbeit'), ('Haushalt', 'Haushalt'), ('Gesundheit', 'Gesundheit'), ('Sonstiges', 'Sonstiges'), ('Einkaufen', 'Einkaufen'), ('Finanzen', 'Finanzen'), ('Bildung', 'Bildung'), ('Sport', 'Sport'), ('Freizeit', 'Freizeit'), ('Familie', 'Familie')], default='Sonstiges', max_length=20, verbose_name='Kategorie'),
        ),
    ]
